version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgresdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: tourplanner
      POSTGRES_PASSWORD: tourplanner
      POSTGRES_DB: tourplannerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./tourplannerApi
    container_name: tourplanner-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tourplannerdb
      SPRING_DATASOURCE_USERNAME: tourplanner
      SPRING_DATASOURCE_PASSWORD: tourplanner

volumes:
  pgdata:
