services:
  db:
    image: postgres:latest
    container_name: postgresdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: tourplanner
      POSTGRES_PASSWORD: tourplanner
      POSTGRES_DB: tourplannerdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
