services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./mvnw:/app/mvnw
      - ./.mvn:/app/.mvn
      - ./pom.xml:/app/pom.xml
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tourplannerdb
      SPRING_DATASOURCE_USERNAME: tourplanner
      SPRING_DATASOURCE_PASSWORD: tourplanner